### ISSUE TITLE
When flags.HelpFlag used, -h shows up as positional arg

### ISSUE THREAD

**Issue by conorr** [jessevdk/go-flags#107]
When I create a parser using `flags.NewParser` and specify the `flags.Default` option so the help message option is added, I am seeing an unexpected result when setting the `-h/--help` option on execution.

When I run a program with the `-h` option, the help message is printed as expected but `-h` gets passed through as a leftover argument. Same goes for `--help`. When I set other options (ones I've defined), those options don't get passed through as leftover arguments.

Is this expected? Here is a gist that shows how I am producing the issue: https://gist.github.com/ctryan3/8dd552b02fdd8ae8efa1

**Comment by jessevdk** [comment]
I went with the easy way out, which is to just not prepend the -h arg to the retargs when the error is `ErrHelp`. @zimmski regarding your proposal, I thought about it and although it does remove some help specific things, it also adds some new that aren't really that useful outside of help. At least currently the special handling of help flags is internal.

I'd still like to see a better way to implement `-h/--help` without all the internal support that we need to do currently. It would be nice if we could find a way for `-h/--help` to work without any of the special tricks we do.
