### ISSUE TITLE
Allow for multi-line string definitions of arg types

### ISSUE THREAD

**Issue by sabhiram** [jessevdk/go-flags#124]
When defining the arguments for a given package, we need to do something like this:

```go
var opts struct {
    Version bool `short:"v" long:"version" description:"Print application version"`
}
```

It would be nice to be able to do:
```go
var opts struct {
    Version bool `
        short:    "v"
        long:     "verbose"
        description: "some text..."`
}
```

**Comment by zimmski** [comment]
We conform to the Go standard. Please have a look at #92.

**Comment by sabhiram** [comment]
Ahh I see, looking at how the tags are being used for xml / json it makes a lot more sense. Sorry, kind of a go-newb here :)

**Comment by zimmski** [comment]
No worries, nothing to be sorry about. I think that this is one feature of Go and especially one convention which needs desperate rethinking.
