### ISSUE TITLE
Any plans on a new release?

### ISSUE THREAD

**Issue by Jmeyering** [jessevdk/go-flags#128]
Would love to grab this from gopkg, but seems were ~300 commits behind using the latest tag.

**Comment by zimmski** [comment]
I am interested in why you are not using the regular import path. I do not know of any breaking API changes in the last dozen commits and I do not think that such changes would be accepted without very good reasons.

**Comment by Jmeyering** [comment]
I am currently using regular import path...I try to use gopkg in every instance outside of the go core library package out of peace of mind primarily. :)

**Comment by jessevdk** [comment]
We only version for breaking changes.

**Comment by Jmeyering** [comment]
I guess I'm curious as to the reasoning behind this? 

gopkg.in is becoming more and more popular and the idea of not locking dependencies to a specific version seems foolish to me.

I don't really think people should have to fork a repository to ensure that no changes are introduced.

**Comment by jessevdk** [comment]
> gopkg.in is becoming more and more popular and the idea of not locking dependencies to a specific version seems foolish to me.

gopkg.in is not the only way to do this. Do you have some numbers about how gopkg.in is becoming more and more popular? I'm not against tagging versions, but honestly go-flags is supposed to be stable so versioning would be pretty arbitrary.
