### ISSUE TITLE
Confusion about "optional" flag

### ISSUE THREAD

**Issue by 3rf** [jessevdk/go-flags#130]
Hi,
I'm trying use the "optional" flag, but it doesn't seem to be working the way I expected it to. What I'd like to do is have a flag, "password", that can be given either with or without arguments. (we need to support an empty --password argument for backwards compatibility)

That is, I'd like
```program --password --otherOption ```
and 
```program --password "mypassword" --otherOption```
to both work. 

Right now I have
	```Password  string `short:"p" long:"password" optional:"yes" description:"password for authentication"` ```
in my options struct. However when I do 
```program --password "mypassword" --otherOption```
the argument to --password is not actually captured, and so "mypassword" ends up in the array of leftover arguments.

Am I misunderstanding what "optional" is for?

**Comment by zimmski** [comment]
Yes I agree, this is a bug.

```go
package main

import (
	"fmt"

	"github.com/jessevdk/go-flags"
)

func main() {
	var opts struct {
		Foo string `long:"foo" optional:"true" optional-value:"no argument"`
		Bar bool   `long:"bar"`
	}

	args, err := flags.Parse(&opts)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	fmt.Printf("Args: %#+v\n", args)
	fmt.Printf("Opts: %#+v\n", opts)
}
```

```
$ go run tt.go --foo --bar
Args: []string{}
Opts: struct { Foo string "long:\"foo\" optional:\"true\" optional-value:\"no argument\""; Bar bool "long:\"bar\"" }{Foo:"no argument", Bar:true}
$ go run tt.go --foo baaaaaa --bar
Args: []string{"baaaaaa"}
Opts: struct { Foo string "long:\"foo\" optional:\"true\" optional-value:\"no argument\""; Bar bool "long:\"bar\"" }{Foo:"no argument", Bar:true}
```

@jessevdk can you confirm that in the last execution "Foo" should use the given argument?

**Comment by jessevdk** [comment]
This is explicit behavior, as per:

https://github.com/jessevdk/go-flags/commit/837238c985d634229928667370802a7a75cba652

This makes long arguments consistent with short arguments. We have been down this road before (can't find the specific issue), and I'm not convinced we should change this behavior (again).

**Comment by 3rf** [comment]
I definitely understand where you're coming from re: consistency, but my team doesn't find the current behavior intuitive given the label of "optional." Given how longstanding this behavior is, I can't really argue that it should be changed, so I have two propositions for you:

1. Let's make the documentation clearer so that others don't misunderstand "optional" again
2. Add another tag or sentinel value for the "optional" tag (ie `optional:"noequals"` or something) in order to change the parser behavior to be what I've described above. This is an awesome library and we'd love to be able to peg our dependencies on this repository instead of a hacked fork of it.

**Comment by jessevdk** [comment]
The issue is not just consistency. The real issue is that with optional arguments as you propose, you simply can't distinguish between an argument being an optional value, or a rest (positional) argument.

1. Yes!
1. I'm not convinced that it's worth making this more complex. The bar to adding more options/tags is getting higher (there are already too many as it is). Moreover, this will change the behavior so it's no longer standard (how do users know about this).

**Comment by jessevdk** [comment]
I've improved the documentation, but I don't think we should change the behavior.
