### ISSUE TITLE
Putting a space in tag loses all flags

### ISSUE THREAD

**Issue by anacrolix** [jessevdk/go-flags#131]
If I have a tag containing `long: "blah"`, all options are lost from the parser, and Parse completes without any usage printed.

**Comment by zimmski** [comment]
This will not happen. We conform to the Go standard. Please have a look at #92.

Also you should check if your parsing produces any errors. Using a malformed tag will produce one.
```go
package main

import (
	"fmt"

	"github.com/jessevdk/go-flags"
)

func main() {
	var opts struct {
		Foo string `long :"bar"`
	}

	_, err := flags.Parse(&opts)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}
}
```

```bash
go run tt.go 
Error: expected `:' after key name, but got `32' (in `long :"bar"`)
```
