### ISSUE TITLE
Errors parsing tags not printed to Stderr

### ISSUE THREAD

**Issue by anacrolix** [jessevdk/go-flags#132]
Errors due to bad tags (ErrTag) aren't printed to Stderr, per PrintErrors option.

**Comment by zimmski** [comment]
This must be discussed with @jessevdk. The documentation states "PrintErrors prints any errors which occurred during parsing to os.Stderr." So personally I see this as a "setup" error and not as parsing error as in argument parsing.

**Comment by jessevdk** [comment]
This is intentional because it is not a parsing error (i.e. something the user of your program did wrong), but a programmer error. Don't forget to check your errors.
