### ISSUE TITLE
Find out if flag has been set?

### ISSUE THREAD

**Issue by mattes** [jessevdk/go-flags#133]
Is it possible to find out if a flag has been set at all?

**Comment by jessevdk** [comment]
We are not exposing this at the moment, although we keep track of this internally. A workaround that would work with the current API would be to use pointers, and check for `nil`. This leads to pretty ugly code though.

There is a private field `Option.isSet` (https://github.com/jessevdk/go-flags/blob/master/option.go#L75) that we could potentially expose. What is your use case?

**Comment by mattes** [comment]
I currently work on v2 of https://github.com/mattes/fugu. It collects options from a file, cli options and docker cli options and finally merges everything together to pass that to docker. 

The issue is the merging here. Fugu needs to know if the user intentionally added a option or if the option  just holds the default value.

The Docker mflag package for example has a [isSet func](https://github.com/docker/docker/blob/e09ead98ef41d14d7e3d8784a0edf29d4afd60f5/pkg/mflag/flag.go#L412) which is really helpful for my purposes.

**Comment by mattes** [comment]
I tried to expose the Option.isSet flag: https://github.com/jessevdk/go-flags/compare/master...mattes:expose-isset

But it seems to return always false?

**Comment by mattes** [comment]
I created 2 pull requests. Both work. While the first one works with a quick getter func the second one exposes isSet by making the var public. Not sure which version you'll like better.

**Comment by mbrt** [comment]
+1 for me, I have a similar use case

**Comment by jessevdk** [comment]
Merged.

**Comment by daulet** [comment]
How does one get list of `Option`s? I don't see it to be exposed by `Parser`. Not to be confused with `Options`.

In other words how to parse args and then check if particular flag has been set?
