### ISSUE TITLE
Global options?

### ISSUE THREAD

**Issue by fd0** [jessevdk/go-flags#141]
First, thanks for the excellent library!

I'm curious if it is possible to have top-level options that are valid as options after a command, i.e. exactly the use-case that (according to the [documentation](https://godoc.org/github.com/jessevdk/go-flags#hdr-Commands)) is not supported. This behavior, unfortunately, confuses users (see https://github.com/restic/restic/issues/198).

Is it maybe possible to define a struct with such global options, embed it in the top-level option struct and again in the command-level option struct? What's the easiest way to merge these two?

I'm looking forward to your comments!

**Comment by jessevdk** [comment]
You could possibly do this, but it does seem very cumbersome and weird. I'd rather just fix things and allow parent command level options to be specified *after* subcommands (i.e. lift the restriction).

**Comment by fd0** [comment]
Huh, I wasn't aware that this is possible. Can you give me a hint?

**Comment by jessevdk** [comment]
I was thinking of something like this:

```go
package main

import "github.com/jessevdk/go-flags"

type Opts struct {
	Value bool `short:"v"`
}

func main() {
	var opts struct {
		*Opts

		Command struct {
			*Opts
		} `command:"cmd"`
	}

	opts.Opts = &Opts{}
	opts.Command.Opts = opts.Opts

	flags.Parse(&opts)
	println(opts.Value)
}
```

But that's definitely hacky :)

I went ahead and just removed the limitation, so command parent options can be specified after the command.

**Comment by fd0** [comment]
Awesome, thanks!
