### ISSUE TITLE
Expose a way to set the description for args for i18n

### ISSUE THREAD

**Issue by mvo5** [jessevdk/go-flags#142]
I currently use something like the following:
```
type cmdInfo struct {
	Verbose    bool `short:"v" long:"verbose" description:"Provides more detailed information"`
}
parser.AddCommand("info", shortInfoHelp, longInfoHelp, &cmdInfo{})
```
and would like to translate the description of "Verbose" using gettext. AFAICT this is not possible right now. Having a interface that would allow me to set the description with something like gettext.Gettext("Provide more detailed information") would be great. 

I'm happy to work on this if there is a chance for the branch to be considered.

**Comment by jessevdk** [comment]
You can do this by setting the `Description` for each option (https://godoc.org/github.com/jessevdk/go-flags#Option.Description) after having created a parser. See docs on how to iterate over options. I don't think this is a large enough use case to consider special support for beyond this.

**Comment by mvo5** [comment]
Thanks for this suggestion! This works for me, I close the issue.
