### ISSUE TITLE
Help displays false default values

### ISSUE THREAD

**Issue by eproxus** [jessevdk/go-flags#143]
Given a option with no default value:

```go
package main

import "github.com/jessevdk/go-flags"

type opts struct {
	Value int `short:"v" description:"The value"`
}

func main() {
	var opts opts
	flags.Parse(&opts)
}
```

Calling help with that option set will display a false default value:

```
$ go run main.go -v 7 -h
Usage:
  main [OPTIONS]

Application Options:
  -v=         The value (7)

Help Options:
  -h, --help  Show this help message
```

This can lead to mistakes where users think there is a default value where there is none.

**Comment by jessevdk** [comment]
The original reason for this was to cover this case:

```go
opts := struct {
    Value int `short:"v" description:"The value"`
} {
    Value: 5
}

flags.Parse(&opts)
```

So the initial value would really be the current value. That said, it obviously doesn't work for your case.

**Comment by eproxus** [comment]
Thanks!
