### ISSUE TITLE
Make default values clearer

### ISSUE THREAD

**Issue by eproxus** [jessevdk/go-flags#145]
It would be nice if go-flags used the same convention as the flag package in Go does when it comes to default values: `Description (default the-value)`. That way it is easier to distinguish between actual default values and parentheses in descriptions.

Consider the following flag:

```go
type opts struct {
	ID string `short:"i" long:"id" description:"Client ID" value-name:"ID" default:"local"`
}
```

It generates the following help text:
```
  -i, --id=ID        Client ID (local)
```

This is ambiguous, does it describe a "local" client ID, or is the default value `local`? A better alternative would be:

```
  -i, --id=ID        Client ID (default local)
```

Or even:
```
  -i, --id=ID        Client ID (default "local")
```

**Comment by GeertJohan** [comment]
+1
I bumped into this recently, but forgot to open an issue.

**Comment by eproxus** [comment]
Agree, for numbers it doesn't make sense. With booleans, it depends on how they are actually parsed. Is `--active=true` parsed as a boolean? If so, then `"true"` would still make sense I think, because it is still a textual value.

**Comment by GeertJohan** [comment]
It makes more sense to print the default in the same way as a literal in Go would be. So ```Active bool `long:"active"```` would be `true`. If Active is of type string, with a default string value of `"true"`, then it makes sense to print `"true"`.

**Comment by eproxus** [comment]
I was thinking, because the help text is for the shell, not the Go code, it makes sense to say that the value is still text.

**Comment by GeertJohan** [comment]
Right, but then numbers are also strings in shell.. So everything would be enclosed by double-quotes. That's why I think it makes more sense to represent the default value in the way it is interpreted.

**Comment by eproxus** [comment]
True, that makes sense.

**Comment by jessevdk** [comment]
Command line arguments are not parsed as literal go values. The idea to show the default values in the help is to show them in the literal format that you would use on the command line, not as you would write them in go. This way you can just copy/paste them on the command line and this makes more sense to me. Prefixing the help default values with `default: ` seems like a good idea though.

**Comment by eproxus** [comment]
Thanks!
