### ISSUE TITLE
suggested -h documentation

### ISSUE THREAD

**Issue by soniah** [jessevdk/go-flags#146]
Thanks Jesse for writing go-flags.

Could I suggest some documentation for handling `-h`? You mention in the documentation that "Furthermore, the special error type ErrHelp is returned. It is up to the caller to exit the program if so desired." I found that not checking for `flags.ErrHelp` and just doing an `os.Exit(1)` resulted in the help being printed twice.

I'm suggesting a sample for the simple case where the programmer just wants to print the help and  exit immediately: https://gist.github.com/soniah/01357b833625b33a0a48

It took me while to work this out (my Go is a bit rusty at the moment) and maybe my code could be improved... Code is from https://github.com/soniah/awsenv

**Comment by jessevdk** [comment]
I'm not sure what exactly is not clear about the behavior of `-h/--help`. It is true that it's a little bit of a strange design in go-flags that the help message is treated as an error, but it sort of works out well. Note that the the documentation of ErrHelp explains that help messages are treated as errors, and that they are automatically printed to stderr if PrintErrors is specified as well. Both these options are enabled in the default case.

The example (in https://github.com/jessevdk/go-flags/blob/master/examples/main.go#L72) also shows how you would write the main parsing in the general case. I.e. you should just exit whenever you get an error and everything should work.
