### ISSUE TITLE
Choices type of command arg?

### ISSUE THREAD

**Issue by smousa** [jessevdk/go-flags#147]
Is there a way to force the user to provide an option based on an enumerated list?

Such as,
find-pet --type[=cat|dog]

**Comment by pksunkara** [comment]
@jessevdk I would really love this. I feel that this is the only thing missing in this package

**Comment by jessevdk** [comment]
I would really like to avoid adding more features at this point. That said, this is something that I like. Note though that you can of course already enforce this by yourself without support in the library, by making the option a callback function and doing the verification in there.

**Comment by pksunkara** [comment]
> by making the option a callback function and doing the verification in there.

Yes, but I am more hoping for an overall UI which means including showing the choices in the help message which is automatically generated.
