### ISSUE TITLE
Way to specify one of list of possible args is required? 

### ISSUE THREAD

**Issue by billybanfield** [jessevdk/go-flags#150]
For example if a program could either take a yml file with -y or a custom encoded file with -e and one of the two must be present for execution but both are handled differently so they need to be specified by different flags.

I'm wondering if this type of functionality exists and I'm not seeing it in the docs, or if it is planned. Seems like it could be a useful feature to add to goflags. 

Love the package by the way.

**Comment by jessevdk** [comment]
This is easily done with a tiny bit of code, checking for https://godoc.org/github.com/jessevdk/go-flags#Option.IsSet, iterating over options and finding the right ones using:

1. https://godoc.org/github.com/jessevdk/go-flags#Command.FindOptionByLongName
1. https://godoc.org/github.com/jessevdk/go-flags#Command.FindOptionByShortName
