### ISSUE TITLE
NewParser initializing pointers where it shouldn't

### ISSUE THREAD

**Issue by errnoh** [jessevdk/go-flags#151]
The following code changes the value of the pointer from nil to random address, which can cause all kinds of unwanted problems:

````
package main

import (
        "fmt"

        "github.com/jessevdk/go-flags"
)

func main() {
        var Test struct {
                Thing *struct{}
        }

        fmt.Println(Test)
        _ = flags.NewParser(&Test, flags.None)
        fmt.Println(Test)
}

**Comment by jessevdk** [comment]
> from nil to random address

No, it just initializes the field with the default empty struct value for your type. This is by design, and was introduced by: https://github.com/jessevdk/go-flags/commit/202f8a632a0e38cce361176b69276590bdbbded0

**Comment by jessevdk** [comment]
The reason for this is that we can't scan correctly scan struct pointers that are nil. I guess we could simply ignore such structs and make it the go-flags user responsibility instead.

**Comment by errnoh** [comment]
Well, if it's by design then obviously you can do what you want. It just
seemed like a bug since the field doesn't have any StructTag field that
go-flags uses.

pe 30. lokakuuta 2015 20.41 Jesse van den Kieboom <notifications@github.com>
kirjoitti:

**Comment by jessevdk** [comment]
I didn't say it was **good** design :smiley:

**Comment by jessevdk** [comment]
go-flags picks up fields from nested structs, so there is no need to tag it specifically. I think I'm keeping the current design.
