### ISSUE TITLE
command specific flags cannot be specified before the command

### ISSUE THREAD

**Issue by cppforlife** [jessevdk/go-flags#154]
Fails: 
`cmd --blah something my-cmd` returns `unknown flag 'blah'`

Works:
`cmd my-cmd --blah something`

Haven't taken a look yet at how parsing is implemented but ideally cmd specific flags could be specified before the cmd. This will be consistent with how global flags can be specified after the cmd.

**Comment by fd0** [comment]
I'd really like to see this feature, my users keep getting confused.

**Comment by jessevdk** [comment]
This is by design and will not change.
