### ISSUE TITLE
Integer argument cannot be negative (can't begin with `-`)

### ISSUE THREAD

**Issue by astockwell** [jessevdk/go-flags#164]
When trying to pass a negative integer as an arg, it appears to break the parser:

```go
package main

import (
	"fmt"

	"github.com/jessevdk/go-flags"
)

type CliOptions struct {
	Value int `short:"v" long:"value" description:"The value (integer)" required:"true"`
}

func main() {
	var cliOptions CliOptions
	_, err := flags.Parse(&cliOptions)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Value: %d\n", cliOptions.Value)
}
```

Execution:

```
go run main.go -v "-5"
expected argument for flag `-v, --value', but got option `-5'
panic: expected argument for flag `-v, --value', but got option `-5'
```

**Comment by jessevdk** [comment]
The recommended solution for this is currently: `go run main.go -v=-5`

The behavior has been discussed multiple times, and especially in this is probably the worst case for it. However, I still feel it's the more consistent and simple parsing behavior. See also https://github.com/jessevdk/go-flags/issues/119 for more information.

**Comment by astockwell** [comment]
Ah nice! Thanks for the work-around. Apologies for filing the duplicate issue, hopefully this will catch a few more search terms going forward.
