### ISSUE TITLE
Support pre-command callback

### ISSUE THREAD

**Issue by atombender** [jessevdk/go-flags#165]
The parser executes the command upon parsing, which is a problem when you want some global options to have an effect on all commands. For example, let's say you want the global option `--debug` to enable debug output. For this to work you have to implement every command this way:

```go
func (c SomeCommand) Execute([]string) error {
  globalOptions.apply()

  // ... normal command logic here
}

// ...

func (globals *GlobalOptions) apply() {
  if globals.Debug {
    logging.SetBackend(debugLogger)
  }
}
```

It would be nice if there were a way to insert a callback that is executed after options have been parsed, but before the command is executed.

**Comment by atombender** [comment]
@jessevdk Thoughts?

**Comment by atombender** [comment]
Thank you!

**Comment by cppforlife** [comment]
@jessevdk any chance we can split parsing from execution? 

here is what we are doing to split parsing from executing: https://github.com/cloudfoundry/bosh-init/blob/cli/cmd/factory.go which allows us to nicely test parsing in isolation: https://github.com/cloudfoundry/bosh-init/blob/cli/cmd/factory_test.go#L133. it works ok but could be prolly made better.

**Comment by jessevdk** [comment]
Testing parsing is part of go-flags testing and can be done easily in isolation by using no-op commands. I'm not sure there is a lot of value to try and separate this out.  Using `CommandHandler` for this case seems a reasonably adequate mechanism.
