### ISSUE TITLE
command help text when no parameters are displayed

### ISSUE THREAD

**Issue by cp16net** [jessevdk/go-flags#166]
I want to display the help text what "command --help" displays if there are no arguments after "command". Currently it does an estimate call to give you what you might have meant if you misspelled something or the list of the commands. Instead of listing all the commands if you just output the help that would be more helpful i think.

Is there a way to default the "command" without arguments to the help text output?
Thanks.

**Comment by zenati** [comment]
Up.

**Comment by jessevdk** [comment]
You can now implement this as follows:

```go
var parser = flags.NewParser(&options, flags.Default)
parser.SubcommandsOptional = true

parser.CommandHandler = func (command flags.Commander, args []string) error {
	if command == nil || len(args) == 0 {
		parser.WriteHelp(os.Stderr)
		return nil
	}

	return command.Execute(args)
}
```
