### ISSUE TITLE
Feature to extend man page output

### ISSUE THREAD

**Issue by blampe** [jessevdk/go-flags#174]
I really love the ability to auto-generate groff for my man pages with `WriteManPage`. The only thing missing for my use case is the option to append some additional sections, e.g., `EXAMPLES`, `CONTACT`, etc.

I could of course write my own groff to the writer after calling `WriteManPage`, but then I end up duplicating helpers like `formatForMan`... I'll probably end up with inconsistencies between my output and go-flags... and who really wants to write groff, anyway? :)

I'm wondering if we could expose something like this:

```
type ManPageSection struct {
    Heading string
    Body string
    Subsections []ManPageSection
}
```

and a function like `FormatManPageSection(s Section) string` to output the section as groff and feed that to the writer.

Curious what your thoughts are here.

**Comment by jessevdk** [comment]
I think this could be interesting, however at this point I would probably prefer if this was developed out as a separate package to avoid growing go-flags with lots of features. Maybe `go-flags-man` ?

**Comment by blampe** [comment]
Definitely, I could see something like this being valuable for a lot of other projects.

**Comment by jessevdk** [comment]
I'm going to close this issue as I do think another library would be better suited here. I'm not planning on writing this library myself, as I personally do not have a need for it. If anybody is up for it, I'd be happen to link to it from the help etc.

**Comment by typekpb** [comment]
@blampe I really like the idea, any plans for providing the library?

**Comment by blampe** [comment]
@typekpb I'm not currently working on it, no. Sorry :)
