### ISSUE TITLE
scan() doesn't handle tabs as whitespace in struct tag `....` field

### ISSUE THREAD

**Issue by jboelter** [jessevdk/go-flags#176]
I formatted my options like below using tabs and it took a bit to figure out what I did wrong. The scan code only skips spaces for whitespace when parsing the struct tag. Support for tabs (or any whitespace?) in the struct tags would be nice. Let me know if you want a pull request or take the snippet below.

```go
var opts struct {
	Verbose          bool   `short:"v"	long:"verbose" 															description:"Show verbose debug information"`
	Local            bool   `short:"l"	long:"local" 															description:"execute locally"`
	Port             int    `short:"p"	long:"port" 		default:"80"  										description:"port to listen for HTTP"`
}
```

```go
func (x *multiTag) scan() (map[string][]string, error) {

...
		// Skip whitespace
		for i < len(v) && (v[i] == ' ' || v[i] == '\t') {
			i++
		}
```

**Comment by jessevdk** [comment]
go-flags follows the go tags spec which does not allow newlines or tabs in tags. I prefer for go-flags to be up to spec so it's easier to explain.

**Comment by jboelter** [comment]
The spec seems to indicate that any [string_lit ](https://golang.org/ref/spec#string_lit)is a valid struct tag. It compiles and doesn't generate any lint or vet warnings.  Is there somewhere else this is spec'd?

[https://golang.org/ref/spec#Struct_types](https://golang.org/ref/spec#Struct_types)
```
StructType     = "struct" "{" { FieldDecl ";" } "}" .
FieldDecl      = (IdentifierList Type | AnonymousField) [ Tag ] .
AnonymousField = [ "*" ] TypeName .
Tag            = string_lit .
```

[https://golang.org/ref/spec#string_lit](https://golang.org/ref/spec#string_lit)

```
string_lit             = raw_string_lit | interpreted_string_lit .
raw_string_lit         = "`" { unicode_char | newline } "`" .
interpreted_string_lit = `"` { unicode_value | byte_value } `"` .
```

**Comment by jessevdk** [comment]
Sorry, I should have been more precise. I was talking about the key/value tag parsing done by the go stdlib: https://golang.org/pkg/reflect/#StructTag
