### ISSUE TITLE
Please consider doing a new upstream release

### ISSUE THREAD

**Issue by zyga** [jessevdk/go-flags#178]
Hey

With my downstream packaging hat on, I'd like to encourage you to do periodic upstream releases. There have been 363 commits on master since the last release.

Best regards
ZK

**Comment by jessevdk** [comment]
Many go packages don't do releases, and go-flags doesn't really either. I'd only release if there is a new breaking change, but that's not the plan. Downstream you can do as you want, but I don't see a reason why go packages would need to be packaged down stream at all.
