### ISSUE TITLE
Feature for a block of text

### ISSUE THREAD

**Issue by lucasem** [jessevdk/go-flags#179]
e.g., I have a few options that take a custom format. It'd be nice to have a dedicated block for it.

```
Application Options:
  --foo=<FORMAT>  does some stuff
  --bar=<FORMAT>  does some other stuff

FORMAT:
  formats have a structure like FIZZ. The escape character is BUZZ, and there are the
  following special fields:

  %a    something
  %b    some other thing
  %c    yet another thing
```

I believe I can achieve this behavior by manually adding the text in, but that feels hacky and I think go-flags should support this in a more direct manner.

**Comment by jessevdk** [comment]
I don't want to add special support for this type of thing. The lower level interfaces should give you the ability to do such things.

In this case, add your own --help option and use https://godoc.org/github.com/jessevdk/go-flags#Parser.WriteHelp to first write the generated help, and then write your own additional help.
