### ISSUE TITLE
How to combine ini and flags?

### ISSUE THREAD

**Issue by raphink** [jessevdk/go-flags#180]
I am currently using `go-flags` for flags+env, e.g.:

```go
type Config struct {
	Engine              string   `short:"E" long:"engine" description:"Backup engine to use." env:"CONPLICITY_ENGINE" default:"duplicity"`
}

var c Config
parser := flags.NewParser(&c, flags.Default)
parser.Parse()
```

I see that are is an `ini.go` file, but I don't see how to plug it in with the generic parser. Is there a way to get values from an IniFile as well, so that values are taken from:

* flags (long/short)
* or environment variable
* or INI file
* or default

**Comment by jessevdk** [comment]
You can do this by creating a new `IniParser` (see https://godoc.org/github.com/jessevdk/go-flags#NewIniParser) and passing it the parser that you created, then call `Parse` on it. By default, flags read from ini files will override default values, but not values that are set by CLI.

**Comment by raphink** [comment]
Thank you for your answer. So I don't need to call parse on both parsers, just the INI one?

**Comment by jessevdk** [comment]
You need to call both the regular `Parse` (first), as well as the `Parse` on the ini parser (second).

**Comment by raphink** [comment]
Thank you.
