### ISSUE TITLE
Feature for hidden choices

### ISSUE THREAD

**Issue by lucasem** [jessevdk/go-flags#181]
A hidden choice would prevent the parser from failing for a choice that shouldn't be shown in the help output but still has functionality.

e.g.:
```go
type Opts struct {
    OutputFormat string `long:"format" choice:"json" choice:"xml" hidden-choice:"gob"`
}
```
with help output:
```
    --format=[json|xml]
```

**Comment by jessevdk** [comment]
I'm not really convinced this needs to be added. The use case for hidden choices seems extremely small. If you want something like this, just implement your own choice validator + help message listing the "visible" choices.
