### ISSUE TITLE
Quoted strings from the shell are not passed through correctly

### ISSUE THREAD

**Issue by prashantv** [jessevdk/go-flags#185]
```go
package main

import (
	"fmt"
	"log"

	"github.com/jessevdk/go-flags"
)

type Options struct {
	RequestBody string `short:"b" long:"body" description:"Request body"`
}

func main() {
	var opts Options
	_, err := flags.Parse(&opts)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Request body:", opts.RequestBody)
}
```

If I run this program with the following arguments, since I am escaping the argument using the shell, I expect the parsed string to contain quotes, but the quotes are lost:
```
$ ./flags -b '"asd"'
Request body: asd
```

And if I try to pass something that is a little more complex, an error is returned:
```
$ ./flags -b '"asd":"yes"'
invalid argument for flag `-b, --body' (expected string): invalid syntax
```

If I do a similar thing with the inbuilt flags package, it works as expected, returning a quoted string in both cases:
```go
package main

import (
	"flag"
	"fmt"
)

var reqBody = flag.String("b", "", "Request body")

func main() {
	flag.Parse()
	fmt.Println("Request body:", *reqBody)
}
```

```
$ ./stdflags -b '"asd"'
Request body: "asd"

$ ./stdflags -b '"asd":"yes"'
Request body: "asd":"yes"
```

**Comment by jessevdk** [comment]
This is currently a "feature", which allows you to easily specify things like \n and \t which get automatically unquoted by go-flags (without relying on the shell). See https://github.com/jessevdk/go-flags/pull/96 for a longer discussion on the rationale. This behavior can be disabled by specifying the `unquote:"false"` tag for a flag.

**Comment by prashantv** [comment]
Thanks for the info @jessevdk. This does seem useful when reading values out of the INI file. I'm not sure if this should be done when parsing flags from the shell however. The linked PR mentions quoting when reading INI files, but doesn't really have much rationale for shell argument unquoting.

**Comment by jessevdk** [comment]
Discussion on support on the CLI starts from here:

https://github.com/jessevdk/go-flags/pull/96#issuecomment-56149029

**Comment by prashantv** [comment]
Fair enough, since it can be disabled, I can just the option. Thanks!
