### ISSUE TITLE
help message should result with exit code 0

### ISSUE THREAD

**Issue by cppforlife** [jessevdk/go-flags#186]
would be nice to make it more consistent with other unix tooling and return exit code 0. 

this may be also related to implementations of --version flag. currently i've implemented it as following how the help command is implemented:

```go
func() error {
		return &goflags.Error{
			Type:    goflags.ErrHelp,
			Message: fmt.Sprintf("version %s", Version),
		}
}
```

what do you think about adding `ExitCode` field to goflags.Error?

cc @vito @cunnie @dpb587

**Comment by jessevdk** [comment]
Adding an `ExitCode` doesn't make too much sense to me. In any case, it's up to the caller program to exit, so you should really just check for `goflags.ErrHelp` and then `os.Exit(0)`.

**Comment by cppforlife** [comment]
@jessevdk agreed on "caller program should exit". though it's a bit weird for each user of go-flags to remember to check for this specific error to avoid considering it a failure.

**Comment by jessevdk** [comment]
I agree it's not very good. The help-as-an-error concept didn't really turn out that well, but it's what we have now. It might be worth adding an `ExitAfterHelp` option that automatically exits after help is shown, to simplify the matter.

**Comment by cppforlife** [comment]
what about just not returning an error out of `ParseArgs`? typically people would write if ParseArgs returned an error exit with non-0.

**Comment by jessevdk** [comment]
Then how would you know that `--help` has happened? In any case, I don't want to break existing programs.

**Comment by cppforlife** [comment]
@jessevdk it's exactly the same situation afaik with any other command. if command succeeds error is not returned.

**Comment by jessevdk** [comment]
Except `--help` is not a command, and also has to work for non-command based CLI.

**Comment by SkYNewZ** [comment]
How do you use `goflags.ErrHelp` ?

```go
parser := flags.NewParser(&config.Options, flags.Default)
_, err := parser.Parse()

if err == flags.ErrHelp {
	os.Exit(0)
}
```

This is not possible and I don't know how to do this…

**Comment by koplas** [comment]
> How do you use `goflags.ErrHelp` ?
> 
> parser := flags.NewParser(&config.Options, flags.Default)
> _, err := parser.Parse()
> 
> if err == flags.ErrHelp {
> 	os.Exit(0)
> }
> 
> This is not possible and I don't know how to do this…

You can use this
```go
if flags.WroteHelp(err) {
	os.Exit(0)
}
```
