### ISSUE TITLE
Can't specify negative numbers for an int

### ISSUE THREAD

**Issue by prashantv** [jessevdk/go-flags#190]
Example code:
```go
type Options struct {
       	Num int `short:"n" long:"num" description:"Number"`
}

func main() {
       	var opts Options
       	_, err := flags.Parse(&opts)
       	if err != nil {
       		log.Fatal(err)
       	}

       	fmt.Println("Num", opts.Num)
}
```

Works fine for 0/positive numbers:
```
$ ./flags -n 0
Num 0
$ ./flags -n 1
Num 1
```

But it fails for negative numbers, since it thinks the `-` is part of an options:
```
$ ./flags -n -1
expected argument for flag `-n, --num', but got option `-1'
``` 

This works fine with the standard library
```go
var n = flag.Int("n", 0, "Num")

func main() {
       	flag.Parse()
       	fmt.Println("Num:", *n)
}
```

```
$ ./stdflags -n 0
Num: 0
$ ./stdflags -n 1
Num: 1
$ ./stdflags -n -1
Num: -1
```

**Comment by jessevdk** [comment]
Normally the answer is that this is not supported, if you want to pass anything as an argument starting with `-`, you need to use the `-n=-1` syntax. However, I made an exception for numbers since it's relatively obvious what the user wants in that case.

**Comment by prashantv** [comment]
Thanks for the quick fix @jessevdk!
