### ISSUE TITLE
cmd --help writes stuff to stderr instead of stdout

### ISSUE THREAD

**Issue by voelzmo** [jessevdk/go-flags#194]
Which makes it impossible to grep for terms in the help.

Expected workflow:
`cmd --help | grep <term>`

What I actually have to do
`cmd --help 2>&1 | grep <term>`

Have run into this multiple times now. Can we switch that to stdout?
And while we're at it: Can we also switch the return code to 0?

**Comment by theckman** [comment]
@voelzmo there's a pattern I've started to work with that let's me write the help to `stdout` and return status `0`. It also lets me unit test any post-processing I do with the flags!

Here is the struct definition and a parse method I define to do the parsing and post-processing: https://github.com/theckman/httpstat/blob/d966c269cf704079dd88d415da840c11d2d1d710/main.go#L61-L118

I then consume it like this in main, and it gives me Exit 0 + stdout for `-h/--help` messages: https://github.com/theckman/httpstat/blob/d966c269cf704079dd88d415da840c11d2d1d710/main.go#L131-L145

You can then basically test the full functionality to ensure you're parsing the right flags and setting the right options: https://github.com/theckman/httpstat/blob/d966c269cf704079dd88d415da840c11d2d1d710/main_test.go#L34-L197

**Comment by jessevdk** [comment]
`--help` is now written to stdout.

**Comment by jessevdk** [comment]
Note that as a library, go-flags will not by itself exit. It's up to the application to properly exit the program with the desired exit code.

**Comment by jessevdk** [comment]
Note 2: I do find it unfortunate in retrospect that go-flags treats `--help` as an error, but I also feel it is not worth the breakage to change this now.
