### ISSUE TITLE
Commands are silently discarded if they have a boolean flag with a default value

### ISSUE THREAD

**Issue by AGFeldman** [jessevdk/go-flags#196]
Caused by https://github.com/jessevdk/go-flags/commit/7f2ab82552ae1b12e070838918ac056507c0f114. If a command has a boolean flag with a default value, then the command disappears. This can be fixed by just removing the default value, but I found the behavior confusing.

**Comment by jessevdk** [comment]
It generates an error, no? This is by design.

**Comment by AGFeldman** [comment]
In our application, I did not see an error generated. The commands vanished silently. (https://github.com/facebookgo/rocks-strata/issues/9 and https://github.com/facebookgo/rocks-strata/issues/25, if you want to dig into it)
