### ISSUE TITLE
semantic versioning request

### ISSUE THREAD

**Issue by MrWako** [jessevdk/go-flags#198]
Hello. I've been using the go-swagger generator (https://github.com/go-swagger/go-swagger) and Glide for package management. Go-swagger depends on go-flags but needs a recent version, more recent than v1. Would it be possible to add some additional semantic version tags (vx.y.z) to your source tree so that we can use Glide's semantic version mechanism over the more recent functionality changes in go-flags.

Thank you.

**Comment by jessevdk** [comment]
Pushed version 1.1 arbitrarily.
