### ISSUE TITLE
If terminal is too small, --help will crash.

### ISSUE THREAD

**Issue by gabrielrussell** [jessevdk/go-flags#199]
At https://github.com/jessevdk/go-flags/blob/master/help.go#L241 , 
If info.terminalColumns is less than descstart, wrapText() will get a negative length and cause a "slice bounds out of range" panic

**Comment by billybanfield** [comment]
hey @jessevdk, can you give some context as to why this was closed?

**Comment by codyn-net** [comment]
This was closed because it was fixed. Do you still encounter this problem?

**Comment by jessevdk** [comment]
It was closed because it was fixed. Do you still encounter the issue?

**Comment by billybanfield** [comment]
My mistake. Hadn't properly revendored! thanks so much.
