### ISSUE TITLE
command with optional positional arg

### ISSUE THREAD

**Issue by cppforlife** [jessevdk/go-flags#203]
Any suggestions how to get following syntax to work:

```
# my-ssh [dest] args...
$ my-ssh 127.0.0.1 sudo cat /boot/grub/grub.conf
$ my-ssh 127.0.0.1 -- sudo cat /boot/grub/grub.conf
$ my-ssh -- sudo cat /boot/grub/grub.conf
```

Problem we are facing is that "sudo" in the last invocation is considered to be the destination. Thanks for any suggestions.

**Comment by cppforlife** [comment]
@jessevdk any thoughts?

**Comment by jessevdk** [comment]
This is simply how rest args work. I'm not sure that we really want more special options to treat double dash differently, but we could add `NonPositionalAfterDoubleDash`? Such options tend to make cmd line argument parsing more inconsistent between different applications however, so I'm not sure it's the right thing to do.

In your case, you'd seem better off detecting whether or not the first positional argument is a resolvable hostname?
