### ISSUE TITLE
How best to merge command line parsed and configuration values?

### ISSUE THREAD

**Issue by goarchit** [jessevdk/go-flags#212]
If there an easy way to determine if a flag was set via the command line vs. via a tag default field?

Trying to resolve a situation where I have a value, lets say PortNum, that has a default value of 2222, but is set in a configuration file to 1111.  If the user flags PortNum to be 2222, it should override the configuration value and return the specified, and coincidentally, the default, value.

My normal logic runs along the lines of:

1) Let go-flags set defaults (very convienent since they show up in --help!), and override via flags.
2) Read Configuration file and override any non-default value (since those would clearly have been set via flags)

My concern is if the user specifies a default value via a flag in order to override the configurtion file setting.

My guess is that  I could use IsSet(), but I'm too new to Go to know how, and I don't see an example I can reference.

**Comment by goarchit** [comment]
Figured out the whole referencing issue.  Good news is that I'm slowly learning Go.  Bad news is it didn't help.  Apparently IsSet() is true if the flag was used, OR if the default value set the option.  I rather like default values being displayed in help.

So I still have an issue of not being able to determine if a user actually used a flag, or if it was just set by default, shy of coding 2 versions of the configuration structure, one with defaults, one without.

e.g. I could call the one without, then read my config file and use IsSet(), then call the one with and see what changed... but that feels rather awkward.  Is there a better way to do this?

**Comment by jessevdk** [comment]
I've added your suggestion for exposing `IsSetDefault`, this is also what the builtin ini config parser, so I think that you should be set for your own configuration format. In the future go-flags might split of the custom configuration parser into a separate package which will make it easier to have your own custom config formats.
