### ISSUE TITLE
How do I specify slices as comma separated values

### ISSUE THREAD

**Issue by ideahitme** [jessevdk/go-flags#215]
**Question:** To read into slice, it seems currently one need to specify the flag multiple times. Is there a way to achieve this via comma separation ?

**Example:**

```
my-app --ips=192.168.0.1,192.168.0.1
```

```
type Options struct {
    IPs []string `long:"ips"`
}
```

**Comment by jessevdk** [comment]
You can do this by creating your own marshaller, or by making your option a function.
