### ISSUE TITLE
required tag is not boolean for flags, but documentation implies it might be

### ISSUE THREAD

**Issue by perolausson** [jessevdk/go-flags#217]
**Problem:**

https://godoc.org/github.com/jessevdk/go-flags#hdr-Available_field_tags

> required:         whether an option is required to appear on the command
                  line. If a required option is not present, the parser will
                  return ErrRequired (optional)

The text stating _whether_ in my opinion means it is a boolean but it isn't a boolean, rather if the _required_ tag is specified, it will be assumed that the flag is required, regardless of what value the _required_ tag actually has. 

**Suggestion:**

It would be useful if _required_ actually was a boolean so that it could be switched on/off as required.

**Example code:**

```
package main

import (
	"fmt"
	"github.com/jessevdk/go-flags"
	"os"
)

func main() {
	var options struct {
		Verbose      string `required:"false" long:"verbose" description:"verbose logging"`
	}
	parser := flags.NewParser(&options, flags.Default)
	if extra_arguments, err := parser.Parse(); err != nil || 0 != len(extra_arguments) {
		if err == nil && 0 != len(extra_arguments) {
			fmt.Println("unknown extra arguments given:")
			for i := range extra_arguments {
				fmt.Println("\t", extra_arguments[i])
			}
		}
		parser.WriteHelp(os.Stderr)
		os.Exit(1)
	}
	fmt.Println("We won't get to here unless --verbose is specified")
}
```

**Comment by jessevdk** [comment]
I don't see a lot of value in this. I understand that it looks a bit strange, but the value of the tag isn't important (it just needs to be present). There is no use case for setting it to false, since it's the default value, and you can't otherwise set/override this. I'll clarify this in the documentation though.

**Comment by perolausson** [comment]
Ok, maybe I should have explained the use case better.

The use case was to enable switches to be mandatory/optional, without having to change tags in the option description. Maybe this isn't as easily done as I would have liked to, but right now it isn't possible.

Thanks for clarifying the docs, I'm sure I'm not the only one who coming from other languages would assume that the value is interpreted and meaningful (eg. python: [argparse](https://docs.python.org/2/library/argparse.html#required)).
