### ISSUE TITLE
Is it possible to defer command execution?

### ISSUE THREAD

**Issue by goarchit** [jessevdk/go-flags#219]
Need to be able to parse flags, enviornments, and whatnot, then do some setup process (like handling 
a configuration file), prior to invoking the parsed command.  Need the staging, since one of the flags
specifies where the configuration file is...

Is this possible, shy of having every command call a configuration file routine?

Just trying to do this cleanly.

Thanks.

**Comment by jessevdk** [comment]
You can use Parser.CommandHandler to set a function that lets you do some work before calling the actual command execute. See https://godoc.org/github.com/jessevdk/go-flags#Parser.

**Comment by goarchit** [comment]
Perfect, thank you!
