### ISSUE TITLE
tab completion to list both long and short options at '-<tab>'

### ISSUE THREAD

**Issue by dkoper** [jessevdk/go-flags#224]
We're currently very excited to add tab completion to our CLI thanks to Goflags' built-in support! Thanks!

For options with short names, tab completion obviously doesn't save us any keypresses.
The important use case here: when I want to know what options are available, tab completion offers them much quicker than opening the man page would.

But for this use case of discovery of available options, it would be more efficient if `cmd -<tab><tab>` returned all options, both long and short.
In particular the long names as they are generally more meaningful.
*To prevent duplication (and excess information) in the case when a flag has both a short and long name, the long name could be displayed while the short name would not.*

Looking at other Linux commands, `gzip -<tab><tab>`, `xz -<tab><tab>` and `apt-get -<tab><tab>` behave this way (on my Ubuntu 14 box).
Other commands (ls, grep) display only their long options, so it seems they don't cater for the use case of option discovery.

**Comment by dkoper** [comment]
@jessevdk Would you be open to a PR to support this?

**Comment by jessevdk** [comment]
Sounds good to me.

**Comment by nickwei84** [comment]
PR: #228

**Comment by jessevdk** [comment]
@dkoper can you verify that this fixes your issue?

**Comment by dkoper** [comment]
@jessevdk Yes, very nice, thanks!!
