### ISSUE TITLE
Setting 'required:"false"' on a boolean flag interprets it as a required field

### ISSUE THREAD

**Issue by pcman312** [jessevdk/go-flags#226]
Expected behavior:
Specifying a boolean opts field with `required:"false"` should error on the parse since a required boolean field doesn't make sense unless you allow for `--no-flag` and a user specified default value.
Example:
```
type Opts struct {
	MyOpt bool `short:"o" long:"myopt" required:"false"`
}
```

Actual Behavior:
Specifying `required:"false"` results in that boolean field being required.

If I specify `required:false` (without the double quotes) it doesn't require the field.

Further investigation revealed that if I specify `required:"true"` on a string field, it correctly requires the field, however if I specify `required:true` without the quotes, it does not get interpreted as a required field. I think what's happening with the boolean field is when you specify it without the double quotes, it fails parsing it and falls back to the default.

**Comment by jessevdk** [comment]
`key:value` is not a valid field tag, must be `name:"value"` (see also https://golang.org/pkg/reflect/#StructTag).

I agree that the behavior of any-content-means-true can be confusing for this flag, I'm willing to make it so at least `"false"` is interpreted as `false` (arguably we should do the same for `"no"` and `"0"`).
