### ISSUE TITLE
Assign a string to flags.Filename

### ISSUE THREAD

**Issue by shwetaskatdare** [jessevdk/go-flags#227]
I have an object with attributes of type flags.Filename. How do I assign dynamically generated string to it ?
for example, both _input_ and _output_ are of type flags.Filename below

str := "hello world" //this will be generated dynamically in the code

opt := &model.TestObj{
           input: "teststring",
           output: str}           ///this line gives an error

**Comment by jessevdk** [comment]
Just like anything in go, you'll need to cast it explicitly, i.e. `flags.Filename(str)`. For the second issue, looks like you have several versions/packages of go-flags being linked in. Types between packages (even if they are actually the same package) aren't compatible.
