### ISSUE TITLE
subcommands vs. "required"

### ISSUE THREAD

**Issue by larham** [jessevdk/go-flags#233]
Can you change the parser to fill in both parent and child command's parameters if they have the same name?

Currently, a subcommand with a required param of same name as parent command will issue an error like "the required flag `--master-host' was not specified"

Here is a sample command parent/child:

```
type VersionCommand struct {
	Master_host   string `long:"master-host" required:"yes" description:"Domain name or IP of host"`
}

type CheckCommand struct {
	Version VersionCommand     `command:"version" alias:"ver" description:"stuff happened here"`
	Master_host string `long:"master-host" required:"yes" description:"Domain name or IP of host"`

```

**Comment by jessevdk** [comment]
Can you explain why your version command needs the same flag as its parent? Can you not just use the parents flag? I think what you're trying to do is just not the way go-flags works.

**Comment by larham** [comment]
Thanks for the feedback. My requirement was that the subcommand have the same flag, but I'll ask the PM about changing that requirement.
