### ISSUE TITLE
Completion for slice types

### ISSUE THREAD

**Issue by jmcarp** [jessevdk/go-flags#235]
Completion works as expected for types that implement `Completer`, like `Filename`, but not for arrays of `Completer` like `[]Filename`. I'm wondering if it would make sense for the completion logic to check for array of `Completer` and if found, return something like `reflect.TypeOf(i).Elem().(Completer).Complete(match)`. Or would that be too magical--would you prefer to require a custom type instead of `[]Filename` to make completion for slices of filename to work?

**Comment by jessevdk** [comment]
Fixed in #236.
