### ISSUE TITLE
Use -h for something other than --help/usage

### ISSUE THREAD

**Issue by tremby** [jessevdk/go-flags#240]
I want to use `-h` as the short version of a `--host` option, rather than for the short version of `--help`. `--help` should still exist, but have no short version.

Is this possible?

**Comment by jessevdk** [comment]
You will have to disable the default help option by removing the [HelpFlag](https://godoc.org/github.com/jessevdk/go-flags#Options) from the default options, using [NewParser](https://godoc.org/github.com/jessevdk/go-flags#NewParser).

```go
NewParser(&opts, flags.Default & ~flags.Help)

// Alternatively:
// NewParser(&opts, flags.PrintErrors | flags.PassDoubleDash)
```

Then, you can add your own help flag like so:

```go
var opts struct {
        ShowHelp func() error `short:"h" long:"help" description:"Show this help message"`
}

opts.ShowHelp = func() error {
        var b bytes.Buffer

	parser.WriteHelp(&b)
	return newError(flags.ErrHelp, b.String())
}
```

Alternatively, instead of returning an error you can directly write help to `os.Stdout` and exit.

**Comment by tremby** [comment]
Thanks.

I managed to fix a couple of issues with your example code (I'm a complete newbie to Go and this library so the fixes weren't immediately obvious to me):

- Bitwise not is `^`, not `~`
- The help option is `flags.HelpFlag`, not `flags.Help`
- `NewParser` is in the `flags` namespace, and I had to actually store the returned parser in a variable

But am still having some trouble.

Right now I have this:

```go
type cliOptions struct {
    MpdHost     string       `short:"h" long:"host" description:"MPD host"`
    ShowHelp    func() error `long:"help" description:"Show this help message"`
}

func main() {
    var opts cliOptions

    parser := flags.NewParser(&opts, flags.Default & ^flags.HelpFlag)

    opts.ShowHelp = func() error {
        var b bytes.Buffer
        parser.WriteHelp(&b)
        return newError(flags.ErrHelp, b.String())
    }

    remainder, err := parser.Parse()
```

I'm getting `unedfined: newError`. I've tried also `flags.newError`, `flags.error.newError`, and some other variants, but I get various similar errors about it not being exported.

Please help!

**Comment by tremby** [comment]
Even if we can get this working, it's not a pleasant solution.

It would be much better for people wanting to use `-h` for something different if there were any of the following possible solutions:

- The parser exposes a function which will render usage. Internally the default `--help`/`-h` option would simply be calling this. A developer such as myself who wants to override the default flags for help simply switches off `HelpFlag` and then chooses their own flags, calling the function where appropriate.
- The parser provides an option to tell it which long and short options should invoke the help, and if they're overridden they replace `short:"h" long:"help"` with whatever is given.
- The parser automatically detects `-h` or `--help` being used for some other option, and disassociates showing usage with these flags in those cases.

**Comment by tremby** [comment]
@jessevdk, any comment?
