### ISSUE TITLE
Best way to use suboptions

### ISSUE THREAD

**Issue by Nhoya** [jessevdk/go-flags#243]
Hey there, 
i'm actually on  a situation where i have an option:

```
Module     string `short:"m" long:"module" description:"Specify module"  choice:"a" choice:"b"  choice:"c" choice:"d"` 
```
There is a way to create sub-options for each choice?
e.g if i use `--module a ` i can select `--foo 123`
but if i use `--module b` i can select `--bar`

**Comment by jessevdk** [comment]
No, there is no way for this. You could think of using commands for this instead.
