### ISSUE TITLE
Is it possible to add flags for subcommand?

### ISSUE THREAD

**Issue by edgar-humberto** [jessevdk/go-flags#247]
I have been struggling to find an example of how to use flags with a given subcommand.

Would love to know if it is possible to do something like the following. 
`mycli bump --major` or `mycli bump --minor` or `mycli bump patch`

**Comment by jessevdk** [comment]
Yes, just define the options on the subcommand struct. For example: https://github.com/jessevdk/go-flags/blob/master/examples/add.go
