### ISSUE TITLE
Feature Request: Add software version to help

### ISSUE THREAD

**Issue by sylr** [jessevdk/go-flags#250]
Hi,

It would be great if we could display the version of the software using go-flags in the output of `--help`.

If convenient, `--version` could also display it if a Flag is set.

Regards.

**Comment by jessevdk** [comment]
You can do this by setting `Usage` on the parser. I don't really want to add any special support for this in go-flags.

**Comment by agentram** [comment]
Please any help how I can print package version. This does not work for me because I have required flags:
```go
type Opts struct {
	Ssh     SshOpts  `group:"SSH Options"`
	Log     LogOpts  `group:"Log Options"`
	Version func()   `long:"version" description:"Print package version"`
}

conf := &Opts{Version: func() {
         fmt.Printf("VERSION: %s\nBUILD: %s \n", VERSION, BUILD)
}}
```
