### ISSUE TITLE
Suggestion for adjusting argument parsing for more predictable behavior

### ISSUE THREAD

**Issue by brittag** [jessevdk/go-flags#253]
Hi! My teammates and I use the Cloud Foundry `cf` CLI tool, which uses this go-flags library. We noticed a behavior we didn't expect, so this is our suggestion for making the behavior more predictable.

In the following scenario, the password starts with a `-` (dash):

`cf login -u username -p -my-password`

In that case, `cf login` returns an error, which can be logged (and cause a security incident) if you're using it in an automated script with a CI/CD tool:

```
Incorrect Usage: expected argument for flag `-p', but got option `-my-password'
```

Our suggestion is that the parser shouldn't treat `-` specially if it follows an option flag that is expected to take an argument.

I understand that changing something like this can have *other* unexpected effects for downstream users, but it may be worth reviewing and comparing to the behavior of other parsers. Thank you!

**Comment by mozillazg** [comment]
GNU recommends use `--` to handle this case.

> The argument ‘--’ terminates all options; any following arguments are treated as non-option arguments, even if they begin with a hyphen.

https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by jessevdk** [comment]
This has been discussed before, but we follow the more or less standard way of dealing with this. Use the `=` syntax to avoid this problem.
