### ISSUE TITLE
Support localisation 

### ISSUE THREAD

**Issue by Naatan** [jessevdk/go-flags#254]
At the moment the output is hardcoded English. It would be nice if this could be overwritten so that it can be localised.

**Comment by Naatan** [comment]
Note the struct tags also become quite difficult to read when injecting variables, eg:

```
var options struct {
	Locale func(string) "long:\"locale\" short:\"L\" description:\""+T("flag_state_locale_description")+"\""
}
````

The core issue here seems to be that go-flags was not designed with localisation in mind.

**Comment by jessevdk** [comment]
It wasn't, and doing localization as in your snippet seems very cumbersome. I wouldn't mind integration with go-i18n, but I would then instead just run i18n as a post-step (after having scanned the metadata, but before parsing). You can simply feed and replace the descriptions of all the options. You can easily do this externally, and I don't want an explicit dependency on i18n. You could develop `go-flags-i18n` quite easily I think.
