### ISSUE TITLE
Error parsing String with spaces!

### ISSUE THREAD

**Issue by discoli** [jessevdk/go-flags#256]
`	Role string `short:"r" long:"role" description:"The role name to be promoted to." required:"true"``

And then I parse the struct, yadiyadiyadah, if I were to input `-r Server Access` it would set the role string to Server not server access.

If I try to use quotes, like `-r "Server Acess"` it tries to tell me that it's expecting a string implying that it's not a string, but like.. ._.

If anyone knows how to fix this or something, that'd be hugely appriciated.
Thanks :cry:

**Comment by notzippy** [comment]
Try single quotes @discoli

**Comment by discoli** [comment]
@notzippy nope, still doesn't work, it only parsed the first bit, from 'Hello world' it finds 'Hello

**Comment by jessevdk** [comment]
What platform, how are you calling the executable? Passing arguments is a shell thing, it has little to do with go-flags.
