### ISSUE TITLE
err info

### ISSUE THREAD

**Issue by littleLj** [jessevdk/go-flags#258]
if  input flag is -h or help, and the parser.Parse() function will return the err info .  
 the errinfo how to set null

**Comment by jessevdk** [comment]
Sorry, I don't fully understand the issue here. Can you please explain the problem?

**Comment by littleLj** [comment]
> I think that @littleLj is reporting the issue that when invoking the `-h` or `--help` flag, `flags.Parse(&opts)` returns an error with a value `!= nil`.
> Is this an expected behavior?

it's not expected .  because  user always use the -h to require the usage of tools.
