### ISSUE TITLE
Disallowing additional parameters almost everywhere

### ISSUE THREAD

**Issue by psaffrey-illumina** [jessevdk/go-flags#261]
I'm using go-flags to build quite a complex command tree - around 15 commands each with up to 10 subcommands and sometimes triply nested commands. A user has noticed that if they mistype an option with too many dashes e.g. `---myoption` instead of `--myoption` this is ignored, rather than being reported as an error because it is treated as an additional argument - something that would appear in the left hand side (the variable `args`) here:

args, err := flags.ParseArgs(&commands, os.Args[1:])

The vast majority of my commands do not require additional arguments - everything is specified in the command/sub-command and option switches - so I would like to flag additional options provided as errors. 

Therefore I have two questions:

- Is there one place where I can flag as an error a user providing an additional argument like this? The most natural place seems to be after the ParseArgs() call I show above, but by this stage the Execute() on the command has already fired and it's too late. 

- If I am able to bulk-disallow extra arguments, would I also be able to make exceptions? As I say, the vast majority of my commands do not take extra arguments, but a handful need to do so. 

I'm trying to avoid having boilerplate in many of my Execute() functions to throw an error if the []string argument is non-empty.

**Comment by jessevdk** [comment]
The simplest way to do this is to set the [Parser.CommandHandler](https://godoc.org/github.com/jessevdk/go-flags#Parser) in the parser to handle this case. You can inspect if there are any rest arguments and then return an error.
