### ISSUE TITLE
Add NoUnQuote Parser Option

### ISSUE THREAD

**Issue by relvacode** [jessevdk/go-flags#262]
Currently the default behaviour is to always unquote a string during parsing unless `unquote:"false"` is explicitly set on each argument field. For some programs the default behaviour may be to never unquote parameters.

A such I would like to propose a new parser option is added named `NoUnQuote` which flips the default behaviour of `unquote` to be false unless explicitly set to true.

**Comment by jessevdk** [comment]
I don't like adding more options that just change defaults for certain cases. You'll just need to specify `unquote:"false"`.
