### ISSUE TITLE
env-namespace broken with 'go modules'

### ISSUE THREAD

**Issue by alexsn** [jessevdk/go-flags#282]
Simple example program:
```
package main

import (
	"fmt"
	"github.com/jessevdk/go-flags"
)

type Option struct {
	Foo string `long:"foo" default:"z" env:"FOO"`
}
type config struct {
	Nested Option `group:"nested" namespace:"nested" env-namespace:"NESTED"`
}

func main() {
	var cfg config
	flags.Parse(&cfg)
	fmt.Println(cfg.Nested.Foo)
}
```

- Running without go modules works as expected:
> ~/t » NESTED_FOO=j go run main.go
j

- Running with go modules enabled causes NESTED_FOO environment to be ignored:

> ~/t » go mod init test 
> go: creating new go.mod: module test
> ~/t » NESTED_FOO=j go run main.go
z

**Comment by alexsn** [comment]
By default go modules uses the latest tagged version which doesn't support env-namespace. Issue can be resolved by running: `go get -u github.com/jessevdk/go-flags@master`

**Comment by tozh** [comment]
Why don't release a new verion?
