### ISSUE TITLE
Time for 1.4.1 or 1.5.0?

### ISSUE THREAD

**Issue by markus-wa** [jessevdk/go-flags#288]
I use `WroteHelp()` and it was a bit confusing that it's not available after a `go get` as go retrieves the most recent tag when using modules (which i am doing).

As a workaround I was able to do a   `go get github.com/jessevdk/go-flags@master`

I'd suggest creating a new tag containing the 40+ commits since `1.4.0`.

**Comment by zikaeroh** [comment]
@zimmski I'm not sure if you still have access as you mentioned in #317. Would you be willing to tag a new release with all of the current changes to help new module users? I can keep pulling this at a master revision (which is fine), but I think it'd be nice to have a new tagged version. I personally keep coming back to this library for my flag parsing needs, so am sad to have seen it stagnate.

**Comment by XenoPhex** [comment]
Bumping for visibility, any chance we can get a new release?

**Comment by markus-wa** [comment]
(very cheeky ping to @zimmski)

**Comment by jessevdk** [comment]
v1.5.0 has been released
