### ISSUE TITLE
File path arguments to flags on Windows are considered "options" and cause failures.

### ISSUE THREAD

**Issue by genevieve** [jessevdk/go-flags#313]
Hey there!

We are using this library for a cli on windows. We have discovered that when we are passing a filepath to a flag, go-flags construes that argument as a flag itself [here](https://github.com/jessevdk/go-flags/blob/1c38ed7ad0cc3d9e66649ac398c30e45f395c4eb/optstyle_windows.go#L17-L19).

Here's what the code looks like:

```go
type options struct {
	Config  string `short:"c" default:"C:\\etc\\cf-assets\\envoy_config\\envoy.yaml"`
}

func main() {
	var o options

	p := flags.NewParser(&o, flags.IgnoreUnknown)
	_, err := p.ParseArgs(os.Args[1:])
	if err != nil {
		log.Fatalf("Flags parse: %s", err)
	}
...
}
```

Here's the failure:
```
Flags parse: expected argument for flag `/c', but got option `/etc/cf-assets/envoy_config/envoy.yaml'
```

Not sure if there's a workaround for this you might recommend.

Thanks!

**Comment by hol430** [comment]
Haven't tested this, but you could try using unix-style options (e.g. -c instead of /c). You do this by building with the `forceposix` tag. e.g. `go build -tags forceposix`.
