### ISSUE TITLE
Would like optional commands

### ISSUE THREAD

**Issue by marius-matioc** [jessevdk/go-flags#320]
Specify certain commands, but accept a command line without any command.
I have an executable that has one main function, for which I would like the user to not need to enter a command, but several helper function, for which commands are needed.

**Comment by jboelter** [comment]
Have you looked at:
````golang
Example ExampleCommand `long:"example" subcommands-optional:"true"`
````
or
````
parser.SubcommandsOptional = true
````
or
````golang
cmd, err := parser.AddCommand("example",
   "example command",
   "example command details",
   &exampleCmd)

   cmd.SubcommandsOptional = true
````

This won't require the user to specific a sub-command.

**Comment by marius-matioc** [comment]
Yes, this works beautifully. Thanks.
