### ISSUE TITLE
bool cannot have default value

### ISSUE THREAD

**Issue by linczy** [jessevdk/go-flags#322]
I dropped this entire framework because default value cannot be declared for bool.
I.e. you want to have an argument dryRun, this definitely should be true by default.
This cannot be setup with this framework.

**Comment by gchaincl** [comment]
I also need this feature, basically being able to define `--foo=true` (which has the same effect of `--foo`) or the opposite `--foo=false`

If this is something that the maintainers find useful I'll be happy to give it a try

**Comment by gchaincl** [comment]
https://github.com/jessevdk/go-flags/issues/80 addresses the issue
