### ISSUE TITLE
Ability to reset env variable after parsing

### ISSUE THREAD

**Issue by agalitsyn** [jessevdk/go-flags#327]
For example I have some data sensitive option like password in my config struct. I would like to set special flag in tags, for example `reset-env`
```go
Secret string `long:"secret" env:"SECRET" description:"Secret for signing JWT" required:"true" reset-env:"true"`
```
And it will reset env variable after parsing, so `printenv` in shell will now show this in output.

For now I can workaround this using such function:
```go
// resetEnv clears sensitive env vars
func resetEnv(envs ...string) {
	for _, env := range envs {
		if err := os.Unsetenv(env); err != nil {
			log.Printf("[WARN] can't unset env %s, %s", env, err)
		}
	}
}
```

But it not convenient when using `env-namespace` feature, and this clear func could easily stop clearing sensitive vars.

**Comment by jessevdk** [comment]
Seems easy enough to extract the EnvNamespace etc from walking the parser structure. I don't think this needs to be built in.
