### ISSUE TITLE
Second go flag and Case Insensitivity 

### ISSUE THREAD

**Issue by vm1234-code** [jessevdk/go-flags#333]
How do I create a second short value in my struct?  
Is there a way to make your short flag case insensitive using go-flags? 
For example if I call a flag:  columnName string `long:"strings" short:"s" description:"column name"`  How would I create a second short call for the flag columnName?

**Comment by jessevdk** [comment]
There is no way to do that. You can only have one short and/or long name for a flag. Flags are case sensitive.
