### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by vdimir** [jessevdk/go-flags#345]
After I faced with same problem as #282 I notices that there wasn't released for a long time, but there are new commits in master. Go module uses latest tag by default, why you don't create release with new features?
I really enjoyed this library and continue using it from master.  I reckon that continuing to create releases will helps to all go module users. I hope this project won't be abandoned. Thanks!

**Comment by mjmac** [comment]
Just adding a +1 to this issue. I realized that our CLI utilities were exiting with 1 instead of 0 after --help. I found the `WroteHelp()` helper in master, but it's not in v1.4.0. :/

**Comment by jessevdk** [comment]
v1.5.0 has been released
