### ISSUE TITLE
When generating man pages, the LongDescription cannot be a multi-line string

### ISSUE THREAD

**Issue by aignas** [jessevdk/go-flags#349]
I noticed, that the long description of a group in the generated man page cannot be a multi-line string, which contains `\n` because the `manQuote` function processes the `\n` runes, which I would like to not be changed in any way, or it would be great to at least split the given string on `\n` characters before passing them to the `formatForMan`.

Code in question.
https://github.com/jessevdk/go-flags/blob/master/man.go#L52

**Comment by jessevdk** [comment]
Should be fixed in upcoming release
