### ISSUE TITLE
How to set array type env variable when use this package 

### ISSUE THREAD

**Issue by wzf1943** [jessevdk/go-flags#351]
Hi when I tried to set array type environment variable for example when I set 

export ARRAY=a,b,c 

The parser of this go-flags package always parse that a,b,c to one string like 

["a,b,c"]

Rather than 

["a", "b", "c"]

How to set this array variable up in env variable?

Thanks

**Comment by jessevdk** [comment]
You can use the `env-delim` tag to specify on which character it should be split. See https://pkg.go.dev/github.com/jessevdk/go-flags#hdr-Available_field_tags and https://github.com/jessevdk/go-flags/blob/6a6df1be4f0285203eafe8e39deca331e34926ff/parser_test.go#L256 for an example.
