### ISSUE TITLE
group.go mixed left quote (`) with single quote (')

### ISSUE THREAD

**Issue by stanleyyzhu** [jessevdk/go-flags#403]
very tiny bug:
group.go: mixed left quote (`) with single quote (')

For example:
"short names can only be 1 character long, not `` ` ``%s`` ' ``"

**Comment by jessevdk** [comment]
This is actual intentional style. See https://stackoverflow.com/questions/1432952/why-do-plain-text-technical-articles-often-enclose-terms-within-backticks-and-si for some background. I don't mind changing it, but I also don't mind keeping it :)
