### ISSUE TITLE
gofumpt removes choice:"..." tags, only first is left

### ISSUE THREAD

**Issue by sk-lemken** [jessevdk/go-flags#411]
I have a problem in a project, where we use auto formatting with [gofumpt](https://github.com/mvdan/gofumpt).

The auto format removes all additional tags with the same tag-name from a field.

## Expect:
```go
var FlagLogLevel string `short:"L" long:"log-level" default:"info" choice:"debug" choice:"info" choice:"warn" choice:"error" description:"Set the log level of the output messages"`
```

## Actual:
```go
var FlagLogLevel string `short:"L" long:"log-level" default:"info" choice:"debug" description:"Set the log level of the output messages"`
```

Maybe someone has an idea what is the cause of this, and how to prevent this.

**Comment by CompuRoot** [comment]
> Maybe someone has an idea what is the cause of this, and how to prevent this.

Isn't this a problem with `gofumpt` ?

Why code formatter touching anything that surrounded by **``** at all ?

IMHO any data shouldn't be touched by any pre-processors
