### ISSUE TITLE
Improper octal conversion due to strconv.ParseInt()

### ISSUE THREAD

**Issue by dwhittle-sfdc** [jessevdk/go-flags#412]
I have a case where I want to pass *nix file permissions as a command line option in standard octal format (e.g. `0600`). Unfortunately it looks like the package [is using](https://github.com/jessevdk/go-flags/blob/main/convert.go#L233) `strconv.ParseInt()` to handle `int` options and it is not doing the correct thing.

Here is a basic [example](https://go.dev/play/p/5TOIB0mdT4L):

Sample code:
```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	fmt.Println(int(0600))
	fmt.Println(strconv.ParseInt("0600", 10, 32))
}
```

Result:
```
384
600 <nil>
```

When the octal is converted to an `int`, 384 is the expected result in this case.

I suppose this is really a Go issue and I should go submit a bug to them, but is this something you think could be fixed here in your package. I'd be happy to submit a PR to patch it, but I have to jump through corporate hoops to get approval first :roll_eyes: I'd rather not bother with that if it's something you wouldn't consider accepting.

**Comment by rasa** [comment]
@dwhittle-sfdc Did you try the `base` tag?
```
base: a base (radix) used to convert strings to integer values, the
      default base is 10 (i.e. decimal) (optional)
```
per https://pkg.go.dev/github.com/jessevdk/go-flags#hdr-Available_field_tags

If that works for you, please close this issue.

**Comment by dwhittle-sfdc** [comment]
:woman_facepalming: 

@rasa Thanks for the pointer. Looks like a few new tag options have been added since I last read the docs (years ago). :frowning_face: 

Thanks
