### ISSUE TITLE
Bool should be able to be set false.

### ISSUE THREAD

**Issue by hfern** [jessevdk/go-flags#80]
If you have a bool option that defaults to true, there is no way of disabling it from the command line. 

You should be able to do this by ./somecommand --boolflag=0

Right now running this results in: "bool flag `boolflag` cannot have an argument"

**Comment by shurcooL** [comment]
> When I need a bool that defaults to true, I inverted the meaning/name for the flag and still default to false.

I agree that's a better practice.

In that case, shouldn't go-flags detect it as an error (at init time) and refuse to work? A user of this package should not be able apply `default:"true"` to a `bool` flag if it renders the flag completely unfit for its purpose (i.e. able to have more than 1 different value).
