### ISSUE TITLE
Example for usage of bash completion

### ISSUE THREAD

**Issue by zimmski** [jessevdk/go-flags#82]
So I am playing around with the new bash completion and it works great (except two things I will correct with pull requests). But I am missing an example for using it in a program. Is this the idiomatic way?

```go
p := flags.NewParser(&opts, flags.Default)

if _, err := p.Parse(); err != nil {
	panic(err)
}

if len(os.Getenv("GO_FLAGS_COMPLETION")) != 0 {
	os.Exit(123)
}

// and now the code of the program
```

If yes, I think we should add a flag or method to indicate that the completion code ran and that the user should stop the program.

**Comment by jessevdk** [comment]
I've added a `CompletionHandler` hook. By default, it will print completion items and Exit(0), which I still believe is the right thing to do. Since this issue there is now also documentation and an example of how to use/enable completion so I'm closing this.
